/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FavoritosImport } from './routes/favoritos'
import { Route as PersonajesIdImport } from './routes/personajes/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const FavoritosRoute = FavoritosImport.update({
  path: '/favoritos',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const PersonajesIdRoute = PersonajesIdImport.update({
  path: '/personajes/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/favoritos': {
      preLoaderRoute: typeof FavoritosImport
      parentRoute: typeof rootRoute
    }
    '/personajes/$id': {
      preLoaderRoute: typeof PersonajesIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  FavoritosRoute,
  PersonajesIdRoute,
])

/* prettier-ignore-end */
